export * from './SignInModal';
export * from './RegisterModal';
export * from './ActivateNewBonusModal';
export * from './AboutBGDModal';
export * from './ChangePasswordModal';
export * from './CollectRewardsModal';
export * from './PromocodeModal';
export * from './StatisticsModal';
export * from './TransactionsModal';
